"""
Run the KPI SQL queries in sql/kpi_queries.sql against the flight data with DuckDB.
Saves each result to results/sql/<name>.csv and prints it.

Usage:
  python src/run_sql.py --data data/southwest_flights.csv
"""
import argparse
import re
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]


def main(data: Path):
    out = ROOT / "results" / "sql"
    out.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect()
    con.execute("CREATE TABLE flights AS SELECT * FROM read_csv_auto(?)", [str(data)])
    print(f"Loaded {con.execute('SELECT COUNT(*) FROM flights').fetchone()[0]:,} rows into DuckDB\n")

    sql = (ROOT / "sql" / "kpi_queries.sql").read_text()
    blocks = re.split(r"^-- name:\s*(\S+)\s*$", sql, flags=re.M)[1:]
    md = ["# SQL KPI Results (auto-generated by `src/run_sql.py`)\n"]
    for name, body in zip(blocks[::2], blocks[1::2]):
        df = con.execute(body.strip().rstrip(";")).df()
        df.to_csv(out / f"{name}.csv", index=False)
        md += [f"## {name}\n", df.to_markdown(index=False), ""]
        print(f"== {name} ==\n{df.head(10).to_string(index=False)}\n")
    (ROOT / "results" / "sql_results.md").write_text("\n".join(md))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=Path, default=ROOT / "data" / "southwest_flights.csv")
    main(ap.parse_args().data)
